services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb:42
    expose:
      - "3306"
    env_file:
      - .env
    restart: always
    networks:
      - inception-net
    volumes:
      - db-data:/var/lib/mysql

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress:42
    expose:
      - "9000"
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: always
    networks:
      - inception-net
    volumes:
      - wp-data:/var/www/html/jdias-mo.42.fr

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx:42
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: always
    networks:
      - inception-net
    volumes:
      - wp-data:/var/www/html/jdias-mo.42.fr

volumes:
  wp-data:
    name: wp-data
    driver: local
    driver_opts:
      type: none
      device: /home/jdias-mo/data/wp
      o: bind
  db-data:
    name: db-data
    driver: local
    driver_opts:
      type: none
      device: /home/jdias-mo/data/db
      o: bind

networks:
  inception-net:
    name: inception-net
    driver: bridge